global:  - job_name: sht4x_read
    static_configs:
      - targets: ['192.168.1.199:30001']

global:%s  - job_name: sht4x_read
    static_configs:
      - targets: ['192.168.1.199:30001']

global:  - job_name: sht4x_read
    static_configs:
      - targets: ['192.168.1.199:30001']

global:
  - job_name: sht4x_read
    static_configs:
      - targets: ['192.168.1.199:30001']

global:
  - job_name: sht4x_read
    static_configs:
      - targets: ['192.168.1.199:30001']

